In [3]:
import numpy as np

inertia_tens = np.array([[3 , 2, 0],
                           [1, 3, 0],
                           [0, 2 , -3]])

eigenvals, eigenvects = np.linalg.eig(inertia_tens)

princp_momts = np.diag(eigenvals)

princp_axes = eigenvects

print("Eigenvalues (Principal Moments of Inertia):")
print(princp_momts)
print("\nEigenvectors (Principal Axes of Rotation):")
print(princp_axes)


Eigenvalues (Principal Moments of Inertia):
[[ 3.  0.  0.]
 [ 0.  3.  0.]
 [ 0.  0. -3.]]

Eigenvectors (Principal Axes of Rotation):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
